version: "3.9"

services:
  my_postgres:
    image: postgres:17
    container_name: collisions_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USERNAME"]
      interval: 5s
      timeout: 5s
      retries: 5

  etl_project:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: etl-proj1-image
    depends_on:
      my_postgres:
        condition: service_healthy
    env_file:
      - .env
