name: proj1env
channels:
  - defaults
dependencies:
  - python==3.12
  - pip
  - numpy=2.0.2
  - pandas=2.3.2
  - python-dateutil=2.9.0.post0
  - pytz=2025.2
  - pyyaml=6.0.2
  - requests=2.32.5
  - pip:
      - dotenv==0.9.9
      - python-dotenv==1.1.1
      - charset-normalizer==3.4.3
      - idna==3.10
      - urllib3==2.5.0
      - certifi==2025.8.3
      - six==1.17.0
      - tzdata==2025.2
      - loguru==0.7.3
      - pg8000
      - pytest
      - sqlalchemy
      - psycopg2-binary
